---
title: "Applying a Multiverse to Snake Habitat Selection"
author1: "Benjamin Michael Marshall*"
author2: "Alexander Bradley Duthie**"
affiliation1: "Biological and Environmental Sciences, Faculty of Natural Sciences, University of Stirling, Stirling, FK9 4LA, Scotland, UK"
affiliation2: "-"
corresponding1: "benjaminmichaelmarshall@gmail.com"
corresponding2: "alexander.duthie@stir.ac.uk"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    template: main.tex
    keep_tex: true
    highlight: monochrome
    fig_caption: true
    dev: pdf
  bookdown::html_document2:
    theme: yeti
    highlight: monochrome
    fig_caption: true
link-citations: yes
linkcolor: gray
bibliography: [multiverseSnakesPrereg_refs.bib, packages_refs.bib]
csl: peerj.csl
editor_options: 
  markdown: 
    wrap: sentence
abstract: abc
keywords: Movement ecology, step selection function, habitat preference, habitat selection, animal movement, multiverse, research choice, researcher degrees for freedom,
---

# Introduction

<!-- Science should be self correcting -->
<!-- Alberts et al 2015 -->

<!-- Self-correction can be more ephemeral, not limited to direct hard replications -->
<!-- Peterson, Panosky 2021 -->

<!-- reproducibility crisis -->
<!-- Baker 2016 -->

* Science should be self correcting

A key component of science is the continual reassessment of past work and findings [@alberts_self-correction_2015].

Whether that takes the form of direct replications aiming to discover how exactly how reliable previous work is, or more integrative approaches testing the edges of previous findings' generalisability and retesting questions in different study systems [@nakagawa_replicating_2015; @peterson_self-correction_2021]. <!-- see peterson paper for definition check . Also add quasi-rep citation --> 

<!-- Direct quote from Peterson 2021 - "When replication in the normal course of integration does not provide clear signals of truth or falsity, researchers instead look for signs of robustness." -->

* Reassessments of old data have reveal inconsistencies

Reassessments and replications --regardless of their position on the direct-quasi continuum-- can aid the formal and organic self-correcting process of science.
Initial findings set the stage for subsequent work, building momentum that can accelerate progress, but also be difficult to redirect if the initial impetus was misdirected [@jennions_relationships_2002; @barto_dissemination_2012] <!-- thinking the progress papers, think it was by barto about early research that is underpowered starting trends that are hard to stop -->.
Therefore, checking and confirming results early is important; we can see this principle recognised in the peer review system itself.

Checking previous findings through replication can be come more difficult in systems with high task uncertainty. 
High task uncertainty systems –those that manifest high levels of uncontrollable stochasticity– may make direct diagnostic replications impractical or impossible, and render the evidence from quasi-replications weaker <!-- peterson pano 2021 is the paper for this stuff -->[@peterson_self-correction_2021].
Ecological systems can be considered as generating high task uncertainty, with many interconnected elements, and when studying wild systems many of those elements are uncontrollable.
<!-- peterson pano 2021 has a bit about "task uncertainty" where high perfectly describes ecology and the hard to control system -->

* We can't always collect more data, rechecking old data and conclusions an (albeit not replaceable) alternative

With ecological systems, such complexity and the difficulty to control an experiment makes the direct replications costly, potentially explaining their rarity [@kelly_rate_2019].
When studying wild animals with a level of direct intervention, repeating experiments/studies might be unethical due to the well-being costs [@Weatherhead2004; @tomotani_great_2021; @robstad_impact_2021; @portugal_externally_2022; @altobelli_methods_2022]. 

<!-- could add a couple more examples here -->
When faced with limited options for direct replications, an alternative, albeit not a replacement, would be to re-examine existing datasets.
Pooling old and new datasets, and reanalysising them may provide insights into broader generalisations.

* Computational reproducibility is important, but sometimes new methods appear that might offer additionally insight or is more robust to data structural issues.
* methods impact results and therefore conclusions, we can see such impact in many analysts and multiverses

In some cases older data may have been collected/recorded in away that enables completely fresh analysis [@kays_movebank_2022].
As methodologies develop, conceptualisations change, and computational power increases, new avenues for examining the same data may materialise [e.g., @noonan_effects_2020].
As these new methods are developed and applied, we may see the conclusions based upon those data change.
There are a growing number of examples demonstrating that the analysis approach can alter the results [@salis_how_2021; @desbureaux_subjective_2021], and that the researchers themselves can be a key source of variation in analysis and results [@silberzahn_many_2018; @huntingtonklein_influence_2021; @gould_same_2023].
These examples elegantly show the possible extent of technical uncertainty present in some systems <!-- peterson and pano term again, needs defining -->.

* movement ecology has seen such development in methods, can we check the conclusions remain the same

Not all disciplines have explored the sources of uncertainty in findings equally.
Prudence would push for examination of uncertainty in all its forms, in particular for fields that already tackle high levels of uncertainty originating from a wild study system.
Movement ecology could be argued to exemplify such a field.
Animals are complex, existing in complex wild ecosystems, with individuality and personality [@stuber_spatial_2022].
Depending on the research question, controls in movement ecology can be difficult to achieve, and replications difficult to justify given the strict ethical limitations on interventionist study.
Movement ecology has also seized the opportunities presented by technological developments, enabling higher resolution tracking of animal movements (e.g., GPS tracking) and more sophisticated analysis that can integrate the high dimensional data [e.g., x-y coordinates, time, acceleration, individual, other covariates of interest; @joo_recent_2022].

Personality and the repeatability of behaviours presents a key component to the uncertainty or variation when attempting to generalise.
However, here we turn to the technical uncertainty, the uncertainty originating from the researcher and how they approach the data.
Previous many analyst projects highlight the potential for analyst-side variation [@silberzahn_many_2018; @huntingtonklein_influence_2021; @gould_same_2023], and previous multiverse explorations of movement ecology methods highlight the variation potentially presented within a synthetic movement dataset <!-- FIRST PREPRINTS HERE -->.
Here we take the multiverse approach further by applying it to a number of real case studies with the aim of exploration whether different analysis approaches could/would have altered the final general conclusions.

<!-- ecology has high "task uncertainty" stemming from high "technical" and "strategic task uncertainty" - Peterson pano 2021 -->

<!-- Peterson pano 2021 has a great line that when task uncertainty is higher and more uncontrollable variables exists then integrative replications are more open to interpretation. -->

* as a case study, we re-examine the findings from __ snake movement studies that all describe a form of habitat selection

We selected a quartet of separate but connected movement ecology studies that attempt to disentangle the habitat selection exhibited by snakes in north-eastern Thailand.
All four cases focus on snakes that come into conflict with humans to some extent, either because of the risks poses from their venom (king cobra, Malayan krait, banded krait), or because of their appetite for domestic livestock (Burmese python).
In all cases the habitat selection results could be used to guide snake conservation efforts, as well as interventions into human behaviour to mitigate human-snake conflict.
With these general goals in mind, we re-examine the movement datasets using a multiverse of habitat selection analysis pathways to reveal whether the same data could lead to different conclusions.

<!-- devezer et al 2021 - reproducing the results doesn't mean that they are more likely correct - pg 10. So instead here we are exploring the likely that conclusions would change, an attempt to gauge uncertainty with a number of ~equally~ valid analysis methods -->

<!-- Direct quote from Peterson 2021 - "When replication in the normal course of integration does not provide clear signals of truth or falsity, researchers instead look for signs of robustness." -->

# Methods

## Study Location
<!-- NE Thailand -->
All four case studies occurred in north eastern Thailand, within Nakhon Ratchashima province.
<!-- SERS -->
Three case studies (king cobra, Burmese python, banded krait) were conducted within the Sakaerat Biosphere Reserve.
The reserve comprises of three zones of management: core, buffer, and transitional
The core is largely primary forest; the buffer surrounds the core and is comprised of forest regeneration efforts, whereas the transitional zone allows more development resulting in a mix of agriculture, settlements, and plantation forest.
Bisecting the transitional zone, and running adjacent to the protected forest areas is a four-lane highway connecting the city of Nakhon Ratchshima to Bangkok.
<!-- SUT University campus -->
The case study (Malayan krait) not in the Sakaerat Biosphere Reserve was undertaken nearer to Nakhon Ratchshima proper, on the Suranaree University of Technology.
The university campus is a mix of scrub forest, open lawn, university buildings, and homes.

<!-- enough detail? and double check the match the orignal papers -->

## Study Species and Hypotheses

Snakes can be difficult to detect in wild scenarios <!-- snake in bush paper -->, forcing a wider and more opportunistic suite of methods to gather adequate sample sizes.
In all the chosen case studies snakes were obtained for study using trapping arrays, active surveying, and notifications from locals.
The local notifications often arose from snakes entering human settlements, and a desire for the snake to be removed.
<!-- maybe summary table here of capture methods -->

The four case studies cover four snake species, each with their own ecology and movements.

### King Cobra

@Marshall2018 and @marshall_no_2020 are concerned with king cobras (*Ophiophagus hannah*).
King cobras are a large (tracked individuals between  <!-- ___m and ___m snout to vent length -->), diurnal, active foraging snake species that depredate snakes and monitor lizards <!-- Jones et al here -->.
While considered a predominately forest dwelling species <!-- IUCN cite -->, they are know to make use of more human altered areas <!-- india stuff -->, which can lead to frequent in human-snake conflict <!-- india and hits close -->.
The extremely low occurrence of king cobra bites in Thailand mean that instances of human-snake conflict are primarily a conservation concern as opposed to human health <!-- CITE -->.

@Marshall2018 does not conclude on an actual selection, instead highlighting the king cobras excursions out of the protected forest.
@marshall_no_2020 looks more specifically at selection, highlighting the importance of semi-natural areas that occupy the banks of irrigation canals and intersection the agricultural areas surrounding the protected forest.
Therefore, we will pool both datasets and examine two non-mutually exclusion hypotheses that can be examined through a unified model.

H~OpHa1~: King Cobras select for semi-natural habitat

H~OpHa2~: King Cobras select for forest habitat

### Burmese Python

@smith_native_2021 describe Burmese python (*Python bivittatus*) habitat selection and movement.
Burmese pythons are large (tracked individuals between  <!-- ___m and ___m snout to vent length -->), ambush predators capable of tacking prey ___% larger than their body mass <!-- CITE -->.
The flexibility in regards to prey size means they are inevitably draw into conflict with humans over livestock, a pattern mirrored across the globe for large snakes <!-- Miranda paper?? -->.

The conclusions of @smith_native_2021 on python habitat selection are not dissimilar to those made on king cobras, with an active selection for areas near water.
The land classification used in @smith_native_2021 was slightly different to @marshall_no_2020, grouping semi-natural areas with larger water bodies (e.g., agricultural ponds).

H~PyBi1~: Burmese Pythons select for areas near water.

### Malayan Krait

@hodges_malayan_2022 examine a smaller species, the Malayan krait (*Bungarus candidus*). 
The Malayan kraits tracked were between __ and __m snout to vent, and all lived on a university campus. 
Malayan kraits like many elapids, have a potent and medically significant venom; bites of Malayan kraits can be fatal.
They are nocturnal and actively foraging, with a suggested preference for frogs and small rodents <!--- CEHCK THIS AND CITE -->.

Unlike the other case studies, @hodges_malayan_2022 is undertaken in a more urban environment.
The scale of the Malayan krait movements meant the study was conducted at a finer spatial scale; habitat types are therefore more finely separated (e.g., buildings vs settlements).
The overall conclusions highlight a number of habitat types that potentially being selected for, and in opposition an avoidance of open areas.

H~BuCa1~: Malayan Kraits select for buildings, settlements, and natural areas.

### Banded Krait

@knierim_spatial_2019 looked at a larger krait species, the banded krait (*Bungarus fasciatus*).
Like its smaller cousin the banded krait is also a nocturnal active forager, with a potent venom.
The banded krait is heavier bodies and grows to longer lengths, tracked individuals ranging from <!--___m and ___m--> snout to vent length
However, unlike the Malayan krait the banded krait appears less tolerant of human disturbance in this region of Thailand and tends to have a more Ophiophagus diet <!-- cite -->.

Banded kraits were entirely located in agricultural land, and like the other krait had movements more conducive to finer habitat classifications.
For example, field margins were found as a key nesting site <!-- nesting with cobra cite -->.
@knierim_spatial_2019 shows that importance is reflected in the movements and habitat selection, as banded kraits follow the linear water or field margin features as opposed to the wider more exposed field areas.

H~BuFa1~: Banded Kraits select for waterways and field edges.

## Multiverse Construction

To explore the variation that could arise when testing the above hypotheses, we constructed a multiverse of analytical choices.
A multiverse is tree of branching paths, where decisions made during analysis spawn multiple branches, each with alternative answers.
Previous work has reveal the importance of data quantity over analysis decisions in determining habitat selection <!-- previous multiverse studies -->, but we are still left with sizeable variation in final answers –and perhaps more importantly answers that offer contradictory conclusions.
The variation in results are similarly present in more practical demonstrations, such as many analysts projects <!-- many analysts -->.

<!-- habitat class -->
Our multiverse starts with two alternative ways of defining the habitats.
Each case study has a map of available habitats, defined as categories.
One approach we used is to examine the habitat selection by retaining these categories, only simplifying them to fit the hypotheses.
This simplification took the habitat(s) of interest and codes them as 1, whereas all other habitats previously indicated in the studies to be avoided/not-selected for are coded as 0.
For example, in the case of king cobras, forest and semi-natural areas were classed as 1, and all other types classed as 0.
We then used the 0/1 classification as a predictor in the habitat selection analyses.
We undertook this simplification to facilitate the repeated use of generic code in the multiverse.
The second approach involved converting the simplified categorical habitat types into continuous rasters, where each cell described the distance to a given habitat type.
We inverted the distances, so that a positive effect in the model mean a positive selection towards a habitat type (resulting in a more intuitive final output).

<!-- methods - following pop level stuff -->
The habitat selection methods we explored can be broadly grouped into three types:
- area based RSF, <!-- compana(?), see what the other multiverse looks like, might be not worth it due to performance -->
- step based SSF and Poisson
- Weighted resource selection based

The first category require a define area of availability, for which random available points can be drawn.
To explore the impact of the definition of available, we created a number of different polygons surrounding the tracking data locations.

The second group, instead of using an available area, use available steps randomly generated for each time step.

Finally, we assessed Weighted Resource Selection Function <!-- alston paper -->.

<!-- notes notes notes notes notes notes notes notes notes notes notes notes notes notes notes -->

# notes

The papers below use distance from feature in the models, we could add an exploration of binary habitats too.
Overall simplify the models just to the habitats of interest.
The python paper has a contrasting grouping of what makes water habitats, do we need to explore alternative groupings of land use types - suspect that we don't but instead use the paper specific definitions (except for the 2018 paper because the number of habitat types is high and ill defined).

Any paper using SSF methods we should summarise to the population level to get an estimate we can plot alongside the multiverse answers.
Won't be a perfect comparison, but least on a similar scale.
So we can get a naive mean of SSF preference for given habitat, and in the case of the population ones we can just use that estimate + CIs.

Each species will get model ran on three landscape configurations:
- original, using whatever method/classification system used, but we will only extract the estimates of direct interest to the hypotheses. Model formula will include all habitat types. This will also provide a means of reproducing the original answers for direct comparison to the other estimates from other decisions pathways. 2018 doesn't have this, so will use 2020 LU data.
- targeted continuous, a distance to landscape feature approach but refined only to landscapes that matter (e.g., inverted distance to semi-nat vs inverted distance to everything else).
- targeted binary, simply hypothesised good habitat versus everything else.

### King Cobra
@Marshall2018; @marshall_no_2020
OPHA
2018 paper doesn't conclude a habitat preference, more focusing on the fact that they do not remain within the forest.
The methods are a major limitation in that regard. 
Best course of action is likely to look at semi-nat areas and forest, and examine the validity of both claims.
Using the results from the iSSF in figure 4 primarily, clear semi-nat preference that works for a clean re-testable hypo, forest preference can be additional motivation to make the 2018 paper worth exploring too.
Didn't actually implement any population level summary, but we are testing general conclusions here.
As the other papers have excluded individuals, what if we do the same here for the 2018 snakes, so we have something just targeting the 2020 paper and then something more general? Would make the targets pipeline more intuitive as all species would have this decision. 
Hypothesis 1: King Cobras show preference for semi-natural habitat
Hypothesis 2: King Cobras show preference for forest habitat


### Burmese Python
@smith_native_2021
PYBI
excluded an individual for the pop-level stuff - possible choice to explore?
Figure 4 shows the clear population pattern preferring water (water bodies and semi-nat areas). Figure 5 shows the preference on an individual level also.
Hypothesis: Burmese Pythons select for areas near water.


### Malayan Krait
@hodges_malayan_2022
BUCA
Had excluded individuals - one simply doesn't have enough data; the other should be included(?) but it remained in one habitat type - possible choice to explore?
Hypothesis: Malayan Kraits select for buildings, settlements, and natural areas.

### Banded Krait
@knierim_spatial_2019
BUFA
Need to see if we can get the LU data.
Hypothesis: Banded Kraits select for waterways and field edges.

# ``` {r openOptions}
# optionsCompleteList <- readRDS(here::here("data", "optionsCompleteList.rds"))
# ```

# Results

# Discussion

## Limitations

## Conclusions

# Acknowledgements

BMM was funded by the Natural Environment Research Council (NERC) via the IAPETUS2 Doctoral Training Partnership.

# Software availablity

In addition to packages already mentioned in the methods we also used the following.

We used *R* `r paste0("v.", version$major, ".", version$minor)` [@base] via *RStudio* v.2023.6.2.561 [@rstudio]. <!-- version has to be manually added because rstudioapi doesn't work in targets -->
We used *here* `r paste0("v.", packageVersion("here"))` [@here] and *qs* `r paste0("v.", packageVersion("qs"))` [@qs] to manage directory addresses and saved objects.

We used *raster* `r paste0("v.", packageVersion("raster"))` [@raster] and *RandomFields* `r paste0("v.", packageVersion("RandomFields"))` [@RandomFields] to aid landscape raster creation alongside NLMR `r paste0("v.", packageVersion("NLMR"))` [@NLMR].

We used *ggplot2* `r paste0("v.", packageVersion("ggplot2"))` for creating figures [@ggplot2], with the expansions: *patchwork* `r paste0("v.", packageVersion("patchwork"))` [@patchwork], *ggridges* `r paste0("v.", packageVersion("ggridges"))` [@ggridges], and *ggdist* `r paste0("v.", packageVersion("ggdist"))` [@ggdist].

We used *brms* `r paste0("v.", packageVersion("brms"))` [@brms] to run Bayesian models, with diagnostics generated used *bayesplot* `r paste0("v.", packageVersion("bayesplot"))` [@bayesplot], *tidybayes* `r paste0("v.", packageVersion("tidybayes"))` [@tidybayes], and *performance* `r paste0("v.", packageVersion("performance"))` [@performance].

We used the *dplyr* `r paste0("v.", packageVersion("dplyr"))` [@dplyr], *tibble* `r paste0("v.", packageVersion("tibble"))` [@tibble],
<!-- *reshape2* `r paste0("v.", packageVersion("reshape2"))` [@reshape2], -->
and *stringr* `r paste0("v.", packageVersion("stringr"))` [@stringr] packages for data manipulation.

We used *sp* `r paste0("v.", packageVersion("sp"))` [@sp], *move* `r paste0("v.", packageVersion("move"))` [@move] for manipulation of spatial data and estimation of space use not otherwise mentioned in the methods.

We used rmarkdown `r paste0("v.", packageVersion("rmarkdown"))` [@rmarkdown2023; @rmarkdown2018; @rmarkdown2020], bookdown `r paste0("v.", packageVersion("bookdown"))` [@bookdown2016; @R-bookdown], tinytex `r paste0("v.", packageVersion("tinytex"))` [@tinytex2019; @tinytex2023], and knitr `r paste0("v.", packageVersion("knitr"))` [@knitr2015; @knitr2014; @knitr2023] packages to generate type-set outputs.

We generated R package citations with the aid of *grateful* `r paste0("v.", packageVersion("grateful"))` [@grateful].

# Data availabilty

<!-- add zenodo archived snapshot of github -->

# Supplementary Material

# References
